#%RAML 1.0 NamedExample
value:
  firstName: "Max"
  lastName: "Mule"
  phoneNumber: "1234567890"
  emailAddress: "maxmule@mulesoft.com"
  userName: "maxmule"
  hashedPassword: "KzhyBhLJ7NKBtpWEF/HAQHB2693pC7ZGLVe64qzZ2cmCzKmta1uV9YE95O"
  hashedSalt: "KzhyBhLJ7NKBtpWEF/HAQHB2693pC7ZGLVe64qzZ2cmCzKmta1uV9YE95OtSXJslp"