#%RAML 1.0 NamedExample
value:
  -
    custId: 1
    firstName: "Max"
    lastName: "Mule"
    phoneNumber: "1234567890"
    emailAddress: "maxmule@mulesoft.com"
    userName: "maxmule"
    hashedPassword: "KzhyBhLJ7NKBtpWEF/HAQHB2693pC7ZGLVe64qzZ2cmCzKmta1uV9YE95O"
    hashedSalt: "KzhyBhLJ7NKBtpWEF/HAQHB2693pC7ZGLVe64qzZ2cmCzKmta1uV9YE95OtSXJslp"
  -
    custId: 2
    firstName: "Minnie"
    lastName: "Mule"
    phoneNumber: "2345678901"
    emailAddress: "minniemule@mulesoft.com"
    userName: "minniemule"
    hashedPassword: "KzhyBhLJ7NKBtpWEF/HAQHB2693pC7ZGLVe64qzZ2cmCzKmta1uV9YE95O"
    hashedSalt: "KzhyBhLJ7NKBtpWEF/HAQHB2693pC7ZGLVe64qzZ2cmCzKmta1uV9YE95OtSXJslp"