#%RAML 1.0 NamedExample
value:
  customer:
    custId: 1
    firstName: "Max"
    lastName: "Mule"
    phoneNumber: "1234567890"
    emailAddress: "maxmule@mulesoft.com"
    userName: "maxmule"
    hashedPassword: "KzhyBhLJ7NKBtpWEF/HAQHB2693pC7ZGLVe64qzZ2cmCzKmta1uV9YE95O"
    hashedSalt: "KzhyBhLJ7NKBtpWEF/HAQHB2693pC7ZGLVe64qzZ2cmCzKmta1uV9YE95OtSXJslp"
  checking:
    accountNumber: "CHK123"
    currentBalance: 12345.67
  saving:
    accountNumber: "SAV123"
    currentBalance: 3456.78
  loan:
    accountNumber: "LOA123"
    currentBalance: -1234.67