#%RAML 1.0 NamedExample
value:
  accountNumber: "LOA123"
  currentBalance: -1234.67
  amountPaidThisMonth: 123.45
  interestPaidThisMonth: 23.45
  terms:
      monthlyPaymentAmount: 123.45
      monthlyInterestRate: 0.0083333
      lateFee: 25.00
      termYears: 5
      creditLimit: 5000.00
      feeRequired: true