#%RAML 1.0 NamedExample
value:
  accountNumber: "SAV123"
  currentBalance: 3456.78
  interestEarned: 34.56
  terms:
      minBalance: 100.00
      interestRate: 0.04
      serviceFee: 25.00
      feeRequired: true