#%RAML 1.0 NamedExample
value:
  -
    transactionTimestamp: 1574436958094
    accountNumber: "CHK123"
    amount: 123.45
    transactionType: "Withdrawal"
  -
    transactionTimestamp: 1574436958095
    accountNumber: "CHK123"
    amount: 234.56
    transactionType: "Deposit"